spring:
  application:
    name: product-app
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    show-sql: true

#  datasource:
#    url: jdbc:h2:mem:jpa
#    initialization-mode: always
#    platform: h2
#    username: user
#    password: secret
#    driver-class-name: org.h2.Driver
#  jpa:
#    open-in-view: false
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: create
#  h2:
#    console.enabled: true